import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Carp Travel",
  description: "Generated by Carp Travel",
  icons: {
    icon: "/src/app/favicon.ico",
  },
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <Head>
        <title>Carp Travel</title>
        <meta
          name="description"
          content={
            metadata.description !== null && metadata.description !== undefined
              ? metadata.description
              : ""
          }
        />
      </Head>
      <body className="relative bg-dark-color text-white-color font-inter">
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
